import { ArrowRight, BrainCircuit, ChevronRight, FolderOpen, Plus, Send, Sparkles, X } from "lucide-react";
import ReactMarkdown from "react-markdown";

export default function ChatPage({ activeSource, setActiveSource, getIcon, sourceMessages, inputMessage, setInputMessage, sendMessage, isTyping, messagesEndRef, setView, chatTurns, chatKey, openThread, documents, openSource, getKind }) {
  return (
      <section className="chat-page"><div className="chat-main"><div className="chat-context"><div className="context-icon">{activeSource ? getIcon(activeSource.source_type,18) : <BrainCircuit size={19}/>}</div><div className="context-label"><span className="eyebrow muted">{activeSource ? "A THREAD ABOUT" : "YOUR KNOWLEDGE SPACE"}</span><strong>{activeSource ? activeSource.title || activeSource.filename : "Open conversation"}</strong></div>{activeSource && <button className="context-clear" onClick={()=>setActiveSource(null)} title="Switch to open conversation"><X size={16}/></button>}<button className="context-library" onClick={()=>setView("library")}><FolderOpen size={15}/> Library</button></div>
        {activeSource?.summary && <div className="summary-strip"><Sparkles size={15}/><p>{activeSource.summary}</p><button onClick={()=>setActiveSource({...activeSource,summary:null})}><X size={14}/></button></div>}
        <div className="messages-area">{sourceMessages.length===0 ? <div className="chat-welcome"><div className="welcome-spark"><Sparkles size={20}/></div><span className="eyebrow muted">A FRESH THREAD</span><h2>{activeSource ? "Let’s explore this together." : "What’s on your mind?"}</h2><p>{activeSource ? "Ask a question and this conversation will stay linked to its source." : "Ask across everything you’ve collected, or pick a source from your library."}</p><div className="suggestion-row"><button onClick={()=>setInputMessage(activeSource ? "Give me the key ideas in this source" : "What themes keep showing up in my library?")}>Find the key ideas <ArrowRight size={13}/></button><button onClick={()=>setView("library")}>Choose a source <FolderOpen size={13}/></button></div></div> : <div className="message-list">{sourceMessages.map((msg,i)=><div className={`message-row ${msg.role}`} key={`${msg.at}-${i}`}><span className={`message-avatar ${msg.role}`}>{msg.role === "user" ? "M" : <BrainCircuit size={15}/>}</span><div className="message-content"><span className="message-name">{msg.role === "user" ? "You" : "Cortex"}</span>{msg.role === "user" ? <p>{msg.content}</p> : <div className="markdown-body"><ReactMarkdown>{msg.content}</ReactMarkdown></div>}</div></div>)}{isTyping&&<div className="message-row assistant"><span className="message-avatar assistant"><BrainCircuit size={15}/></span><div className="typing-dots"><i/><i/><i/></div></div>}<div ref={messagesEndRef}/></div>}</div>
        <div className="composer-wrap"><form className="composer" onSubmit={sendMessage}><textarea value={inputMessage} onChange={e=>setInputMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage(e);}}} placeholder={activeSource ? `Ask about ${activeSource.title || activeSource.filename}…` : "Ask anything across your knowledge…"} rows={1}/><div className="composer-bottom"><span><Sparkles size={13}/> Answers grounded in your space</span><button type="submit" disabled={isTyping||!inputMessage.trim()} aria-label="Send message"><Send size={16}/></button></div></form><div className="composer-hint">Enter to send <span>·</span> Shift + Enter for a new line</div></div></div>
        <aside className="thread-sidebar"><div className="thread-sidebar-head"><span className="eyebrow muted">YOUR THREADS</span><button className="icon-soft" title="Open a space-wide conversation" onClick={()=>setActiveSource(null)}><Plus size={16}/></button></div>{chatTurns.length===0 ? <div className="sidebar-empty"><div className="thread-visual"><span/><span/><span/></div><p>Your conversations will show up here, connected to the sources that inspire them.</p></div> : <div className="sidebar-threads">{chatTurns.map((t,i)=><button className={`sidebar-thread ${t.sourceId===chatKey?"current":""}`} key={t.sourceId} onClick={()=>openThread(t.sourceId)}><span className="thread-line"><i/></span><span className="sidebar-thread-copy"><strong>{t.title}</strong><small>{t.count} {t.count===1?"question":"questions"}</small></span>{i===0&&<span className="thread-live"/>}</button>)}</div>}<div className="sidebar-bottom"><div className="source-shelf-title"><span className="eyebrow muted">SOURCE SHELF</span><button onClick={()=>setView("library")}>See all</button></div>{documents.slice(0,5).map(doc=><button key={doc.document_id} className={`shelf-source ${activeSource?.document_id===doc.document_id?"active":""}`} onClick={()=>openSource(doc)}><span className={`source-glyph glyph-${getKind(doc)==="images"?"image":getKind(doc)==="links"?"link":"doc"}`}>{getIcon(doc.source_type,15)}</span><span>{doc.title||doc.filename}</span><ChevronRight size={13}/></button>)}{documents.length===0&&<p className="shelf-empty">Your sources will find a home here.</p>}</div></aside></section>
  );
}
