import { ArrowDownLeft, ArrowRight, BrainCircuit, ChevronRight, FileText, Image as ImageIcon, Link, MessageCircle, Sparkles } from "lucide-react";
import "./Hero.css";

export default function HomePage({ documents, chatTurns, categoryCards, setCategory, setView, openSource, openThread, getIcon }) {
  return (
      <section className="home-page">
        <div className="home-hero">
          <div className="hero-copy"><div className="eyebrow"><Sparkles size={13}/> YOUR SECOND BRAIN, IN MOTION</div><h1>Good ideas have<br/><em>room to wander.</em></h1><p>A home for the things you learn, collect, and connect along the way.</p><button className="primary-button" onClick={() => setView("chat")}><MessageCircle size={16}/> Start a conversation <ArrowRight size={15}/></button><div className="hero-live"><span className="live-pulse"/> YOUR SPACE IS READY <span className="hero-live-sep">·</span> {documents.length} SOURCES CONNECTED</div></div>
          <div className="orbit-scene" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;e.currentTarget.style.setProperty("--pointer-x",`${x*18}deg`);e.currentTarget.style.setProperty("--pointer-y",`${y*-18}deg`);e.currentTarget.style.setProperty("--gaze-x",`${x*2}px`);e.currentTarget.style.setProperty("--gaze-y",`${y*2}px`);}} onPointerLeave={e=>{e.currentTarget.style.setProperty("--pointer-x","0deg");e.currentTarget.style.setProperty("--pointer-y","0deg");e.currentTarget.style.setProperty("--gaze-x","0px");e.currentTarget.style.setProperty("--gaze-y","0px");}}>
            <svg className="orbit-links" viewBox="0 0 340 340" aria-hidden="true"><path className="link-path path-image" d="M54 117 C84 117 112 148 145 163"/><path className="link-path path-note" d="M286 92 C245 105 223 139 194 160"/><path className="link-path path-chat" d="M282 254 C241 235 222 202 194 184"/><path className="link-path path-link" d="M57 254 C91 235 117 205 145 185"/><circle className="link-node node-image" cx="54" cy="117" r="3"/><circle className="link-node node-note" cx="286" cy="92" r="3"/><circle className="link-node node-chat" cx="282" cy="254" r="3"/><circle className="link-node node-link" cx="57" cy="254" r="3"/></svg>
            <div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="orbit orbit-four"/>
            <span className="avatar-whisper"><i/> I’m here. What are we curious about?</span><button className="orbit-core" aria-label="Start a conversation" onClick={()=>setView("chat")}><span className="avatar-aura"/><span className="avatar-face"><span className="avatar-eye eye-left"/><span className="avatar-eye eye-right"/><span className="avatar-smile"/><span className="avatar-cheek cheek-left"/><span className="avatar-cheek cheek-right"/></span><span className="avatar-orb-icon"><BrainCircuit size={13}/></span><span className="avatar-status"/></button>
            <button className="float-token token-image" aria-label="Browse images" onClick={()=>{setCategory("images");setView("library");}}><ImageIcon size={18}/><span className="token-tooltip">Image fragments</span></button><button className="float-token token-note" aria-label="Browse documents" onClick={()=>{setCategory("documents");setView("library");}}><FileText size={18}/><span className="token-tooltip">Notes & documents</span></button><button className="float-token token-chat" aria-label="Open threads" onClick={()=>{setCategory("threads");setView("library");}}><MessageCircle size={18}/><span className="token-tooltip">Conversation threads</span></button><button className="float-token token-link" aria-label="Browse links" onClick={()=>{setCategory("links");setView("library");}}><Link size={17}/><span className="token-tooltip">Web connections</span></button>
            <span className="spark-dot dot-a"/><span className="spark-dot dot-b"/><span className="spark-dot dot-c"/><span className="spark-dot dot-d"/>
            <span className="orbit-label orbit-label-top"><i/> CORTEX NODE <b>01</b></span><span className="orbit-label orbit-label-bottom">MINDSPACE <i/></span>
            <span className="orbit-hud"><span className="hud-mark"><Sparkles size={11}/></span><span><b>{documents.length.toString().padStart(2,"0")}</b><small>signals in orbit</small></span><i className="hud-wave"><b/><b/><b/><b/><b/></i></span>
          </div>
          <div className="hero-grid-overlay"/><div className="hero-scanline"/><div className="hero-grain"/></div>
        <div className="content-width">
          <div className="section-heading"><div><span className="eyebrow muted">YOUR LITTLE UNIVERSE</span><h2>Pick up where curiosity takes you</h2></div><button className="text-button" onClick={() => { setCategory("all"); setView("library"); }}>Open your library <ArrowRight size={15}/></button></div>
          <div className="inventory-grid">{categoryCards.map(({id,label,note,icon:Icon,color,count}) => <button key={id} className={`inventory-card ${color}`} onClick={() => { setCategory(id === "chats" ? "threads" : id); setView("library"); }}><span className="inventory-icon"><Icon size={21}/></span><span className="inventory-copy"><strong>{label}</strong><small>{note}</small></span><span className="inventory-count">{count.toString().padStart(2,"0")}</span><span className="card-arrow"><ArrowDownLeft size={15}/></span><span className="card-art" aria-hidden="true"><Icon size={94}/></span></button>)}</div>
          <div className="lower-grid"><section className="recent-panel"><div className="panel-head"><div><span className="eyebrow muted">FRESHLY CONNECTED</span><h3>Recent in your space</h3></div><button className="icon-soft" onClick={() => setView("library")}><ArrowRight size={16}/></button></div>{documents.length === 0 ? <div className="empty-inline"><span className="empty-orb"><Sparkles size={18}/></span><div><strong>Your space is ready to grow</strong><p>Drop in an image, a note, or a link to start building connections.</p></div></div> : <div className="recent-list">{documents.slice(0,4).map((doc,i)=><button className="recent-item" key={doc.document_id} onClick={()=>openSource(doc)}><span className={`source-glyph glyph-${doc.source_type === "image" ? "image" : doc.source_type === "url" ? "link" : "doc"}`}>{getIcon(doc.source_type,17)}</span><span className="recent-title"><strong>{doc.title || doc.filename}</strong><small>{doc.source_type === "url" ? "Web link" : doc.source_type === "image" ? "Image" : "Document"}</small></span><span className="recent-index">0{i+1}</span><ChevronRight size={15}/></button>)}</div>}</section>
            <section className="threads-panel"><div className="panel-head"><div><span className="eyebrow muted">FOLLOW THE THREAD</span><h3>Loose connections</h3></div><span className="connected-count"><span/> {chatTurns.length} threads</span></div>{chatTurns.length === 0 ? <div className="thread-empty"><div className="thread-visual"><span/><span/><span/></div><p>Chats become pathways through your ideas.</p><button className="text-button" onClick={()=>setView("chat")}>Start the first thread <ArrowRight size={14}/></button></div> : <div className="thread-list">{chatTurns.slice(0,3).map(t=><button className="thread-row" key={t.sourceId} onClick={()=>openThread(t.sourceId)}><span className="thread-node"><MessageCircle size={15}/></span><span><strong>{t.title}</strong><small>{t.count} {t.count === 1 ? "question" : "questions"}</small></span><ArrowRight size={14}/></button>)}</div>}</section></div>
        </div>
      </section>
  );
}
